import { useMemo } from 'react';
import { GitPullRequest } from 'lucide-react';
import { PanelCard } from '../ui/PanelCard';
import { KpiCard } from '../ui/KpiCard';
import { Spinner } from '../ui/Spinner';
import { BarChart, NEON_COLORS } from '../charts';
import { useMetrics } from '../../hooks/useMetrics';
import { useFilterStore } from '../../store/filterStore';
import { applyFilters, getPRSummaryTotals } from '../../utils';

export function PRSummariesPanel() {
  const { data, loading, error } = useMetrics();
  const { languages, editors, models } = useFilterStore();

  const { filtered, chartData, total } = useMemo(() => {
    if (!data || data.length === 0) {
      return { filtered: [], chartData: [] as Record<string, unknown>[], total: 0 };
    }
    const f = applyFilters(data, { languages, editors, models });
    const { total: t, repos } = getPRSummaryTotals(f);
    const cd = repos.slice(0, 10).map((r) => ({
      name: r.name.length > 20 ? `${r.name.slice(0, 18)}…` : r.name,
      'PR Summaries': r.count,
    }));
    return { filtered: f, chartData: cd, total: t };
  }, [data, languages, editors, models]);

  if (loading) return <Spinner />;
  if (error) return <div className="text-neon-magenta text-sm p-4">Error: {error}</div>;
  if (filtered.length === 0) return <div className="text-gray-500 text-sm p-4">No data available</div>;

  return (
    <PanelCard
      id="pr-summaries"
      title="PR Summaries"
      neonColor="blue"
      infoTitle="PR Summaries"
      infoDescription="Pull request summaries generated by Copilot across repositories."
      infoDocsUrl="https://docs.github.com/en/rest/copilot/copilot-metrics"
    >
      <div className="mb-4">
        <KpiCard label="Total PR Summaries" value={total.toLocaleString()} icon={<GitPullRequest size={18} />} neonColor="neon-blue" />
      </div>
      {chartData.length > 0 ? (
        <BarChart
          data={chartData}
          dataKeys={['PR Summaries']}
          colors={[NEON_COLORS.blue]}
          height={Math.max(200, chartData.length * 40)}
        />
      ) : (
        <div className="text-gray-500 text-sm text-center py-8">No PR summary data available</div>
      )}
    </PanelCard>
  );
}
